// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 244);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 3);
    lv_obj_set_y(ui_Button2, 120);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -10);
    lv_obj_set_y(ui_Label7, -137);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Clippits");

    ui_Label8 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -4);
    lv_obj_set_y(ui_Label8, 120);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Program Tag");

    ui_TextArea4 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea4, 150);
    lv_obj_set_height(ui_TextArea4, 38);
    lv_obj_set_x(ui_TextArea4, 75);
    lv_obj_set_y(ui_TextArea4, -80);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4, "Room 2");
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");



    ui_TextArea5 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea5, 150);
    lv_obj_set_height(ui_TextArea5, 38);
    lv_obj_set_x(ui_TextArea5, 75);
    lv_obj_set_y(ui_TextArea5, -31);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea5, "Fiber");
    lv_textarea_set_placeholder_text(ui_TextArea5, "Placeholder...");



    ui_TextArea6 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea6, 150);
    lv_obj_set_height(ui_TextArea6, 38);
    lv_obj_set_x(ui_TextArea6, 75);
    lv_obj_set_y(ui_TextArea6, 19);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea6, "Fred");
    lv_textarea_set_placeholder_text(ui_TextArea6, "Placeholder...");



    ui_Switch2 = lv_switch_create(ui_Screen3);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 23);
    lv_obj_set_y(ui_Switch2, 58);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Label9 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -154);
    lv_obj_set_y(ui_Label9, -80);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Location");

    ui_Label10 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -144);
    lv_obj_set_y(ui_Label10, -34);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Cable Type");

    ui_Label11 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -151);
    lv_obj_set_y(ui_Label11, 15);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Installer");

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -157);
    lv_obj_set_y(ui_Label12, 54);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Pulled");

    ui_Image2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image2, &ui_img_clippitslogo_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 500
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 235
    lv_obj_set_x(ui_Image2, -2);
    lv_obj_set_y(ui_Image2, -51);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image2, 900);
    lv_img_set_zoom(ui_Image2, 128);

}
